services:
  - type: web
    name: image-blur-app-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_prod:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
